--=================================== RELEASED FOR CHEATSHUB.CC =========================================---
--=========================================================================================---
--===================== Mouse Bind Keys / Keyboard bind Keys (only logiitech)==========================---

--======== Rifles ========--
local Phantom = 3
local Phantom_Keyboard = nil
local Vandal = 4
local Vandal_Keyboard = nil
local Bulldog = nil
local Bulldog_Keyboard = nil
--======== SMGs ========--
local Spectre = 5
local Spectre_Keyboard = nil
local Stinger = nil
local Stinger_Keyboard = nil
--======== SideArm ========--
local Frenzy = 6
local Frenzy_Keyboard = nil
--======== Heavy ========--
--- Coming soon ----
--========================================================================================---

EnablePrimaryMouseButtonEvents(true);
local recoil = falseB
local weapon = 0
function OnEvent(event, arg)
 if (event == "MOUSE_BUTTON_PRESSED" and arg == Phantom) or
(event == "G_PRESSED" and arg == Phantom_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Phantom\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Phantom\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
 elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Vandal) or
(event == "G_PRESSED" and arg == Vandal_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Vandal\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Vandal\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Stinger) or
(event == "G_PRESSED" and arg == Stinger_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Stinger\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Stinger\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Frenzy) or
(event == "G_PRESSED" and arg == Frenzy_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Frenzy\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Frenzy\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
 elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Spectre) or
(event == "G_PRESSED" and arg == Spectre_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Spectre\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Spectre\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
 elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Bulldog) or
(event == "G_PRESSED" and arg == Bulldog_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Bulldog\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Bulldog\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
end
  if IsMouseButtonPressed(1) and recoil then
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
    if weapon == Phantom or weapon == Phantom_Keyboard then
       while IsMouseButtonPressed(1) do
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,2)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(-2,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(-2,5)
        MoveMouseRelative(0,5)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,5)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(-2,5)
        Sleep(24)
        MoveMouseRelative(-2,6)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(1,1)
        Sleep(24)
        MoveMouseRelative(1,1)
        Sleep(24)
        MoveMouseRelative(1,1)
        Sleep(24)
        MoveMouseRelative(1,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(3,0.2)
        Sleep(24)
        MoveMouseRelative(5,0.2)
        Sleep(24)
        MoveMouseRelative(5,0.2)
        Sleep(24)
        MoveMouseRelative(3,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2) --Dexter---
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(-1,1)
        Sleep(24)
        MoveMouseRelative(-3,1)
        Sleep(24)
        MoveMouseRelative(-5,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-5,1)
        Sleep(24)
        MoveMouseRelative(-2,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) --Dexter--
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
        ReleaseMouseButton(1)
     end
--------------------------------------------------------------------------------------------
 elseif weapon == Frenzy or weapon == Frenzy_Keyboard then
       while IsMouseButtonPressed(1) do
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,2)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(-2,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(-2,5)
        MoveMouseRelative(0,5)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,5)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(-2,5)
        Sleep(24)
        MoveMouseRelative(-2,6)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(1,1)
        Sleep(24)
        MoveMouseRelative(1,1)
        Sleep(24)
        MoveMouseRelative(1,1)
        Sleep(24)
        MoveMouseRelative(1,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(3,0.2)
        Sleep(24)
        MoveMouseRelative(5,0.2)
        Sleep(24)
        MoveMouseRelative(5,0.2)
        Sleep(24)
        MoveMouseRelative(3,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2) --Dexter---
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(-1,1)
        Sleep(24)
        MoveMouseRelative(-3,1)
        Sleep(24)
        MoveMouseRelative(-5,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-5,1)
        Sleep(24)
        MoveMouseRelative(-2,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) --Dexter--
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
        ReleaseMouseButton(1)
     end

--------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------

   elseif weapon == Vandal or weapon ==Vandal_Keyboard then
       while IsMouseButtonPressed(1) do
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,5)
        MoveMouseRelative(0,5)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,5)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,6)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,5)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(6,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(5,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
       MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(-3,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-3,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
       MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(-7,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
        ReleaseMouseButton(1)
end
------------------------------------------------------------------------------
elseif weapon == Stinger or weapon == Stinger_Keyboard then
       while IsMouseButtonPressed(1) do
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,7)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,7)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        MoveMouseRelative(0,2)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,2)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(2,1)
        Sleep(24)
        MoveMouseRelative(2,1)
        Sleep(24)
        MoveMouseRelative(2,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(3,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(3,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(6,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(5,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
       MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(-3,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-3,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
       MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(-7,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
        ReleaseMouseButton(1)
end
--------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
 elseif weapon == Bulldog or weapon == Bulldog_Keyboard then
       while IsMouseButtonPressed(1) do
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,2)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,5)
        MoveMouseRelative(0,5)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,5)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,6)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(6,1)
        Sleep(24)
        MoveMouseRelative(6,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(-4,0.2)
        Sleep(24)
        MoveMouseRelative(-4,0.2)
        Sleep(24)
        MoveMouseRelative(-4,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0) ---Dexter---
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
        ReleaseMouseButton(1)
     end
-----------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------

 elseif weapon == Spectre or weapon == Spectre_Keyboard then
       while IsMouseButtonPressed(1) do
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,2)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,5)
        MoveMouseRelative(0,5)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,5)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,6)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(-3,4)---
        Sleep(24)
        MoveMouseRelative(-3,4)
        Sleep(24)
        MoveMouseRelative(-3,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(6,1)
        Sleep(24)
        MoveMouseRelative(5,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-3,1)
        Sleep(24)
        MoveMouseRelative(-4,0)
        Sleep(24)
        MoveMouseRelative(-5,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
        ReleaseMouseButton(1)
     end
end
end
end